version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: payflow-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: payflow
      POSTGRES_PASSWORD: payflow123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payflow"]
      interval: 10s
      retries: 5

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    environment:
      - EUREKA_URI=http://discovery-service:8761/eureka
      - JWT_SECRET=payflow-super-secret-key-2024-tfg

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/auth_db
      - DB_USER=payflow
      - DB_PASS=payflow123
      - EUREKA_URI=http://discovery-service:8761/eureka
      - JWT_SECRET=payflow-super-secret-key-2024-tfg

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/transactions_db
      - DB_USER=payflow
      - DB_PASS=payflow123
      - EUREKA_URI=http://discovery-service:8761/eureka

  wallet-service:
    build: ./wallet-service
    container_name: wallet-service
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/wallet_db
      - DB_USER=payflow
      - DB_PASS=payflow123
      - EUREKA_URI=http://discovery-service:8761/eureka

  bank-service:
    build: ./bank-service
    container_name: bank-service
    ports:
      - "8085:8085"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/bank_db
      - DB_USER=payflow
      - DB_PASS=payflow123
      - EUREKA_URI=http://discovery-service:8761/eureka

  invoicing-service:
    build: ./invoicing-service
    container_name: invoicing-service
    ports:
      - "8086:8086"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/invoicing_db
      - DB_USER=payflow
      - DB_PASS=payflow123
      - EUREKA_URI=http://discovery-service:8761/eureka

volumes:
  postgres_data:
