server.port=8085
spring.application.name=bank-service
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bank_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:payflow123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
management.endpoints.web.exposure.include=health
nordigen.base-url=https://bankaccountdata.gocardless.com/api/v2
nordigen.secret-id=${NORDIGEN_SECRET_ID:demo}
nordigen.secret-key=${NORDIGEN_SECRET_KEY:demo}
transaction.service.url=${TRANSACTION_SERVICE_URL:http://localhost:8082}
