server.port=8082
spring.application.name=transaction-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/transactions_db}
spring.datasource.username=${DB_USER:spendiq}
spring.datasource.password=${DB_PASS:spendiq123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}

ibm.mq.queueManager=${MQ_QUEUE_MANAGER:QM1}
ibm.mq.channel=${MQ_CHANNEL:DEV.APP.SVRCONN}
ibm.mq.connName=${MQ_HOST:localhost}(${MQ_PORT:1414})
ibm.mq.user=${MQ_USER:app}
ibm.mq.password=${MQ_PASSWORD:passw0rd}

management.endpoints.web.exposure.include=health
