server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "http://localhost:*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-public
          uri: lb://auth-service
          predicates:
            - Path=/auth/login, /auth/register, /auth/reset-password

        - id: auth-protected
          uri: lb://auth-service
          predicates:
            - Path=/auth/me
          filters:
            - name: JwtAuthFilter

        - id: payments
          uri: lb://auth-service
          predicates:
            - Path=/payments/**
          filters:
            - name: JwtAuthFilter

        - id: transactions
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
          filters:
            - name: JwtAuthFilter

        - id: admin
          uri: lb://auth-service
          predicates:
            - Path=/admin/**
          filters:
            - name: AdminRoleFilter

        - id: wallet
          uri: lb://wallet-service
          predicates:
            - Path=/wallet/**
          filters:
            - name: JwtAuthFilter

        - id: bank-public
          uri: lb://bank-service
          predicates:
            - Path=/bank/callback, /bank/institutions

        - id: bank
          uri: lb://bank-service
          predicates:
            - Path=/bank/**
          filters:
            - name: JwtAuthFilter

        - id: invoices
          uri: lb://invoicing-service
          predicates:
            - Path=/invoices/**
          filters:
            - name: JwtAuthFilter

        - id: expenses
          uri: lb://invoicing-service
          predicates:
            - Path=/expenses/**
          filters:
            - name: JwtAuthFilter

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

app:
  jwt:
    secret: ${JWT_SECRET:payflow-super-secret-key-2024-tfg}
